# Generated by Django 5.2.13 on 2026-07-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_time', models.FloatField(help_text='Seconds required to produce one part')),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
