# Generated by Django 5.2.13 on 2026-07-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=20, unique=True)),
                ('camera_name', models.CharField(max_length=100)),
                ('cycle_time', models.FloatField(help_text='Seconds per part')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='ProductionSettings',
        ),
    ]
